<a href="https://colab.research.google.com/github/endnef2/big_leader/blob/main/DL/day3_subject.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [2]:
import pandas as pd

df = pd.read_excel('/content/drive/MyDrive/Colab Notebooks/DL/dataset/VMI_data.xls')
df

,Part Number,D일06~08(08)H 투입계획(발주) 수량,D일08~10(10)H 투입계획(발주) 수량,D일10~12(13)H 투입계획(발주) 수량,D일13~15(15)H 투입계획(발주) 수량,D일15~17(18)H 투입계획(발주) 수량,D일18~20(21)H 투입계획(발주) 수량,D일21~23(23)H 투입계획(발주) 수량,D일23~01(02)H 투입계획(발주) 수량,D일 02~04H 투입계획 수량,...,D+23일 투입예정 수량,D+24일 투입예정 수량,D+25일 투입예정 수량,D+26일 투입예정 수량,D+27일 투입예정 수량,D+28일 투입예정 수량,D+29일 투입예정 수량,D+30일 투입예정 수량,D+31~D+45일 투입예정 수량,CRET_TIME
0,Part 0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,202109131830
1,Part 1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,202109131830
2,Part 2,139,60,80,76,68,81,68,44,0,...,0,0,0,0,0,0,0,0,0,202109131830
3,Part 3,15,11,17,13,12,16,12,8,0,...,0,0,0,0,0,0,0,0,0,202109131830
4,Part 4,40,27,29,17,18,29,18,9,0,...,0,0,0,0,0,0,0,0,0,202109131830
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17359,Part 105,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,202111010703
17360,Part 112,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,202111010703
17361,Part 106,141,51,69,55,48,0,0,0,0,...,0,0,0,0,0,0,0,0,0,202111010703
17362,Part 107,104,33,46,46,40,0,0,0,0,...,0,0,0,0,0,0,0,0,0,202111010703
17363,Part 108,0,5,1,0,0,0,0,0,0,...,0,16,28,0,0,0,0,0,0,202111010703

In [3]:
df.describe()

,D일06~08(08)H 투입계획(발주) 수량,D일08~10(10)H 투입계획(발주) 수량,D일10~12(13)H 투입계획(발주) 수량,D일13~15(15)H 투입계획(발주) 수량,D일15~17(18)H 투입계획(발주) 수량,D일18~20(21)H 투입계획(발주) 수량,D일21~23(23)H 투입계획(발주) 수량,D일23~01(02)H 투입계획(발주) 수량,D일 02~04H 투입계획 수량,D일 04~06H 투입계획 수량,...,D+23일 투입예정 수량,D+24일 투입예정 수량,D+25일 투입예정 수량,D+26일 투입예정 수량,D+27일 투입예정 수량,D+28일 투입예정 수량,D+29일 투입예정 수량,D+30일 투입예정 수량,D+31~D+45일 투입예정 수량,CRET_TIME
count,17364.000000,17364.000000,17364.000000,17364.000000,17364.000000,17364.000000,17364.000000,17364.000000,17364.0,17364.0,...,17364.000000,17364.000000,17364.000000,17364.000000,17364.000000,17364.000000,17364.000000,17364.000000,17364.000000,1.736400e+04
mean,27.647489,10.158489,12.960954,11.155494,10.138563,12.898065,10.012555,6.339668,0.0,0.0,...,7.002246,11.002764,9.000691,6.231917,4.547455,3.376641,1.159813,0.613050,0.575731,2.021098e+11
std,49.081979,17.098089,21.815280,18.823029,17.104455,21.828078,17.127839,11.088126,0.0,0.0,...,45.697314,53.079274,49.322970,45.566436,38.420002,30.452150,14.697478,9.875954,10.606802,4.582329e+05
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.021091e+11
25%,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.021093e+11
50%,8.000000,3.000000,3.000000,3.000000,3.000000,3.000000,2.000000,1.000000,0.0,0.0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.021101e+11
75%,33.000000,12.000000,16.000000,14.000000,12.000000,15.000000,12.000000,8.000000,0.0,0.0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.021102e+11
max,404.000000,110.000000,137.000000,123.000000,111.000000,140.000000,109.000000,65.000000,0.0,0.0,...,811.000000,798.000000,601.000000,846.000000,753.000000,544.000000,338.000000,302.000000,320.000000,2.021110e+11

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17364 entries, 0 to 17363
Data columns (total 84 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Part Number               17364 non-null  object
 1   D일06~08(08)H 투입계획(발주) 수량  17364 non-null  int64
 2   D일08~10(10)H 투입계획(발주) 수량  17364 non-null  int64
 3   D일10~12(13)H 투입계획(발주) 수량  17364 non-null  int64
 4   D일13~15(15)H 투입계획(발주) 수량  17364 non-null  int64
 5   D일15~17(18)H 투입계획(발주) 수량  17364 non-null  int64
 6   D일18~20(21)H 투입계획(발주) 수량  17364 non-null  int64
 7   D일21~23(23)H 투입계획(발주) 수량  17364 non-null  int64
 8   D일23~01(02)H 투입계획(발주) 수량  17364 non-null  int64
 9   D일 02~04H 투입계획 수량         17364 non-null  int64
 10  D일 04~06H 투입계획 수량         17364 non-null  int64
 11  D일 투입예정 수량(D일계획)          17364 non-null  int64
 12  D+1일 투입예정 수량(D+1일)        17364 non-null  int64
 13  D+1일 투입예정 수량(D+1일).1      17364 non-null  int64
 14  D+1일 투입예정 수량(D+1일).2      17364 non-null  int64
 15  D+1일 투입예정 수량(D+1일).3      17364 non-null  int64
 16  D+1일 투입예정 수량(D+1일).4      17364 non-null  int64
 17  D+1일 투입예정 수량(D+1일).5      17364 non-null  int64
 18  D+1일 투입예정 수량(D+1일).6      17364 non-null  int64
 19  D+1일 투입예정 수량(D+1일).7      17364 non-null  int64
 20  D+1일 투입예정 수량(D+1일).8      17364 non-null  int64
 21  D+1일 투입예정 수량(D+1일).9      17364 non-null  int64
 22  D+1일 투입예정 수량(Total)       17364 non-null  int64
 23  D+2일 투입예정 수량(과부족수량)       17364 non-null  int64
 24  D+2일 투입예정 수량(과부족수량).1     17364 non-null  int64
 25  D+2일 투입예정 수량(과부족수량).2     17364 non-null  int64
 26  D+2일 투입예정 수량(과부족수량).3     17364 non-null  int64
 27  D+2일 투입예정 수량(과부족수량).4     17364 non-null  int64
 28  D+2일 투입예정 수량(과부족수량).5     17364 non-null  int64
 29  D+2일 투입예정 수량(과부족수량).6     17364 non-null  int64
 30  D+2일 투입예정 수량(과부족수량).7     17364 non-null  int64
 31  D+2일 투입예정 수량(과부족수량).8     17364 non-null  int64
 32  D+2일 투입예정 수량(과부족수량).9     17364 non-null  int64
 33  D+2일 투입예정 수량(Total)       17364 non-null  int64
 34  D+3일 투입예정 수량(과부족수량)       17364 non-null  int64
 35  D+3일 투입예정 수량(과부족수량).1     17364 non-null  int64
 36  D+3일 투입예정 수량(과부족수량).2     17364 non-null  int64
 37  D+3일 투입예정 수량(과부족수량).3     17364 non-null  int64
 38  D+3일 투입예정 수량(과부족수량).4     17364 non-null  int64
 39  D+3일 투입예정 수량(과부족수량).5     17364 non-null  int64
 40  D+3일 투입예정 수량(과부족수량).6     17364 non-null  int64
 41  D+3일 투입예정 수량(과부족수량).7     17364 non-null  int64
 42  D+3일 투입예정 수량(과부족수량).8     17364 non-null  int64
 43  D+3일 투입예정 수량(과부족수량).9     17364 non-null  int64
 44  D+3일 투입예정 수량(Total)       17364 non-null  int64
 45  D+4일 투입예정 수량(과부족수량)       17364 non-null  int64
 46  D+4일 투입예정 수량(과부족수량).1     17364 non-null  int64
 47  D+4일 투입예정 수량(과부족수량).2     17364 non-null  int64
 48  D+4일 투입예정 수량(과부족수량).3     17364 non-null  int64
 49  D+4일 투입예정 수량(과부족수량).4     17364 non-null  int64
 50  D+4일 투입예정 수량(과부족수량).5     17364 non-null  int64
 51  D+4일 투입예정 수량(과부족수량).6     17364 non-null  int64
 52  D+4일 투입예정 수량(과부족수량).7     17364 non-null  int64
 53  D+4일 투입예정 수량(과부족수량).8     17364 non-null  int64
 54  D+4일 투입예정 수량(과부족수량).9     17364 non-null  int64
 55  D+4일 투입예정 수량(Total)       17364 non-null  int64
 56  D+5일 투입예정 수량              17364 non-null  int64
 57  D+6일 투입예정 수량              17364 non-null  int64
 58  D+7일 투입예정 수량              17364 non-null  int64
 59  D+8일 투입예정 수량              17364 non-null  int64
 60  D+9일 투입예정 수량              17364 non-null  int64
 61  D+10일 투입예정 수량             17364 non-null  int64
 62  D+11일 투입예정 수량             17364 non-null  int64
 63  D+12일 투입예정 수량             17364 non-null  int64
 64  D+13일 투입예정 수량             17364 non-null  int64
 65  D+14일 투입예정 수량             17364 non-null  int64
 66  D+15일 투입예정 수량             17364 non-null  int64
 67  D+16일 투입예정 수량             17364 non-null  int64
 68  D+17일 투입예정 수량             17364 non-null  int64
 69  D+18일 투입예정 수량             17364 non-null  int64
 70  D+19일 투입예정 수량             17364 non-null  int64
 71  D+20일 투입예정 수량             17364 non-null  int64
 72  D+21일 투입예정 수량             17364 non-null  int64
 73  D+22일 투입예정 수량             17364 non-null  int64
 74  D+23일 투입예정 수량             17364 non-null  int64
 75  D+24일 투입예정 수량             17364 non-null  int64
 76  D+25일 투입예정 수량             17364 non-null  int64
 77  D+26일 투입예정 수량             17364 non-null  int64
 78  D+27일 투입예정 수량             17364 non-null  int64
 79  D+28일 투입예정 수량             17364 non-null  int64
 80  D+29일 투입예정 수량             17364 non-null  int64
 81  D+30일 투입예정 수량             17364 non-null  int64
 82  D+31~D+45일 투입예정 수량        17364 non-null  int64
 83  CRET_TIME                 17364 non-null  int64
dtypes: int64(83), object(1)
memory usage: 11.1+ MB

In [5]:
df.isnull().sum().any() # 결측치는 없음

False

In [6]:
df.columns

Index(['Part Number', 'D일06~08(08)H 투입계획(발주) 수량', 'D일08~10(10)H 투입계획(발주) 수량',
       'D일10~12(13)H 투입계획(발주) 수량', 'D일13~15(15)H 투입계획(발주) 수량',
       'D일15~17(18)H 투입계획(발주) 수량', 'D일18~20(21)H 투입계획(발주) 수량',
       'D일21~23(23)H 투입계획(발주) 수량', 'D일23~01(02)H 투입계획(발주) 수량',
       'D일 02~04H 투입계획 수량', 'D일 04~06H 투입계획 수량', 'D일 투입예정 수량(D일계획)',
       'D+1일 투입예정 수량(D+1일)', 'D+1일 투입예정 수량(D+1일).1', 'D+1일 투입예정 수량(D+1일).2',
       'D+1일 투입예정 수량(D+1일).3', 'D+1일 투입예정 수량(D+1일).4', 'D+1일 투입예정 수량(D+1일).5',
       'D+1일 투입예정 수량(D+1일).6', 'D+1일 투입예정 수량(D+1일).7', 'D+1일 투입예정 수량(D+1일).8',
       'D+1일 투입예정 수량(D+1일).9', 'D+1일 투입예정 수량(Total)', 'D+2일 투입예정 수량(과부족수량)',
       'D+2일 투입예정 수량(과부족수량).1', 'D+2일 투입예정 수량(과부족수량).2',
       'D+2일 투입예정 수량(과부족수량).3', 'D+2일 투입예정 수량(과부족수량).4',
       'D+2일 투입예정 수량(과부족수량).5', 'D+2일 투입예정 수량(과부족수량).6',
       'D+2일 투입예정 수량(과부족수량).7', 'D+2일 투입예정 수량(과부족수량).8',
       'D+2일 투입예정 수량(과부족수량).9', 'D+2일 투입예정 수량(Total)', 'D+3일 투입예정 수량(과부족수량)',
       'D+3일 투입예정 수량(과부족수량).1', 'D+3일 투입예정 수량(과부족수량).2',
       'D+3일 투입예정 수량(과부족수량).3', 'D+3일 투입예정 수량(과부족수량).4',
       'D+3일 투입예정 수량(과부족수량).5', 'D+3일 투입예정 수량(과부족수량).6',
       'D+3일 투입예정 수량(과부족수량).7', 'D+3일 투입예정 수량(과부족수량).8',
       'D+3일 투입예정 수량(과부족수량).9', 'D+3일 투입예정 수량(Total)', 'D+4일 투입예정 수량(과부족수량)',
       'D+4일 투입예정 수량(과부족수량).1', 'D+4일 투입예정 수량(과부족수량).2',
       'D+4일 투입예정 수량(과부족수량).3', 'D+4일 투입예정 수량(과부족수량).4',
       'D+4일 투입예정 수량(과부족수량).5', 'D+4일 투입예정 수량(과부족수량).6',
       'D+4일 투입예정 수량(과부족수량).7', 'D+4일 투입예정 수량(과부족수량).8',
       'D+4일 투입예정 수량(과부족수량).9', 'D+4일 투입예정 수량(Total)', 'D+5일 투입예정 수량',
       'D+6일 투입예정 수량', 'D+7일 투입예정 수량', 'D+8일 투입예정 수량', 'D+9일 투입예정 수량',
       'D+10일 투입예정 수량', 'D+11일 투입예정 수량', 'D+12일 투입예정 수량', 'D+13일 투입예정 수량',
       'D+14일 투입예정 수량', 'D+15일 투입예정 수량', 'D+16일 투입예정 수량', 'D+17일 투입예정 수량',
       'D+18일 투입예정 수량', 'D+19일 투입예정 수량', 'D+20일 투입예정 수량', 'D+21일 투입예정 수량',
       'D+22일 투입예정 수량', 'D+23일 투입예정 수량', 'D+24일 투입예정 수량', 'D+25일 투입예정 수량',
       'D+26일 투입예정 수량', 'D+27일 투입예정 수량', 'D+28일 투입예정 수량', 'D+29일 투입예정 수량',
       'D+30일 투입예정 수량', 'D+31~D+45일 투입예정 수량', 'CRET_TIME'],
      dtype='object')

In [7]:
df.head(1)

,Part Number,D일06~08(08)H 투입계획(발주) 수량,D일08~10(10)H 투입계획(발주) 수량,D일10~12(13)H 투입계획(발주) 수량,D일13~15(15)H 투입계획(발주) 수량,D일15~17(18)H 투입계획(발주) 수량,D일18~20(21)H 투입계획(발주) 수량,D일21~23(23)H 투입계획(발주) 수량,D일23~01(02)H 투입계획(발주) 수량,D일 02~04H 투입계획 수량,...,D+23일 투입예정 수량,D+24일 투입예정 수량,D+25일 투입예정 수량,D+26일 투입예정 수량,D+27일 투입예정 수량,D+28일 투입예정 수량,D+29일 투입예정 수량,D+30일 투입예정 수량,D+31~D+45일 투입예정 수량,CRET_TIME
0,Part 0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,202109131830

In [8]:
df['CRET_TIME'] = pd.to_datetime(df['CRET_TIME'], format='%Y%m%d%H%M%S')

## 1. 중복 삭제 후 pivot table 생성

In [9]:
df.drop_duplicates(subset=["Part Number", "CRET_TIME"], inplace=True)
pivot_table = df.pivot(index="Part Number", columns="CRET_TIME", values="D일 투입예정 수량(D일계획)")
pivot_table

CRET_TIME,2021-09-13 18:03:00,2021-09-14 06:00:05,2021-09-14 06:02:05,2021-09-14 06:03:04,2021-09-14 17:03:00,2021-09-15 06:02:00,2021-09-15 06:03:07,2021-09-15 16:03:03,2021-09-16 06:03:02,2021-09-16 06:03:08,...,2021-10-28 15:03:00,2021-10-28 16:02:06,2021-10-29 06:03:00,2021-10-29 06:03:02,2021-10-29 07:00:06,2021-10-29 12:03:04,2021-10-29 15:00:03,2021-10-29 15:03:08,2021-10-30 07:00:04,2021-11-01 07:00:03
Part Number,,,,,,,,,,,,,,,,,,,,,
Part 0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Part 1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Part 10,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,23.0,23.0,...,178.0,178.0,178.0,156.0,156.0,156.0,156.0,156.0,156.0,104.0
Part 100,38.0,38.0,35.0,35.0,35.0,40.0,40.0,40.0,38.0,38.0,...,33.0,33.0,33.0,23.0,23.0,23.0,23.0,23.0,23.0,0.0
Part 101,0.0,0.0,0.0,0.0,0.0,77.0,77.0,77.0,78.0,78.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Part 95,113.0,113.0,209.0,209.0,209.0,209.0,209.0,209.0,288.0,288.0,...,276.0,276.0,276.0,264.0,264.0,264.0,264.0,264.0,264.0,209.0
Part 96,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,0.0,0.0,...,6.0,6.0,6.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Part 97,127.0,127.0,32.0,32.0,32.0,28.0,28.0,28.0,28.0,28.0,...,4.0,4.0,4.0,3.0,3.0,3.0,3.0,3.0,3.0,1.0
Part 98,40.0,40.0,33.0,33.0,33.0,43.0,43.0,43.0,42.0,42.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Part 99,124.0,124.0,150.0,150.0,150.0,48.0,48.0,48.0,39.0,39.0,...,46.0,46.0,46.0,49.0,49.0,49.0,49.0,49.0,49.0,11.0

In [10]:
pivot_table.fillna(0, inplace=True)

In [11]:
pivot_table.columns

DatetimeIndex(['2021-09-13 18:03:00', '2021-09-14 06:00:05',
               '2021-09-14 06:02:05', '2021-09-14 06:03:04',
               '2021-09-14 17:03:00', '2021-09-15 06:02:00',
               '2021-09-15 06:03:07', '2021-09-15 16:03:03',
               '2021-09-16 06:03:02', '2021-09-16 06:03:08',
               ...
               '2021-10-28 15:03:00', '2021-10-28 16:02:06',
               '2021-10-29 06:03:00', '2021-10-29 06:03:02',
               '2021-10-29 07:00:06', '2021-10-29 12:03:04',
               '2021-10-29 15:00:03', '2021-10-29 15:03:08',
               '2021-10-30 07:00:04', '2021-11-01 07:00:03'],
              dtype='datetime64[ns]', name='CRET_TIME', length=153, freq=None)

In [12]:
pivot_table.shape

(117, 153)

In [13]:
pivot_table.isnull().sum()

CRET_TIME
2021-09-13 18:03:00    0
2021-09-14 06:00:05    0
2021-09-14 06:02:05    0
2021-09-14 06:03:04    0
2021-09-14 17:03:00    0
                      ..
2021-10-29 12:03:04    0
2021-10-29 15:00:03    0
2021-10-29 15:03:08    0
2021-10-30 07:00:04    0
2021-11-01 07:00:03    0
Length: 153, dtype: int64

In [14]:
import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [15]:
type(pivot_table)

pandas.core.frame.DataFrame

## 2. Train/Test split

In [52]:
X = pivot_table.iloc[:, :-10]

In [53]:
y = pivot_table.iloc[:, -10:]

In [54]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y,
                                                    train_size = 0.8,
                                                    random_state=100)
X_train.shape, X_test.shape

((93, 143), (24, 143))

In [55]:
from sklearn.preprocessing import StandardScaler

standardScaler = StandardScaler().fit(X_train)
X_train = standardScaler.transform(X_train)
X_test = standardScaler.transform(X_test)

In [44]:
# from sklearn.preprocessing import MinMaxScaler

# minmaxscaler = MinMaxScaler().fit(X_train)
# X_train = minmaxscaler.transform(X_train)
# X_test = minmaxscaler.transform(X_test)

## 3. DataLoader 구축

In [56]:
from torch.utils.data import TensorDataset, DataLoader

X_train = np.array(X_train).astype(np.float32)
y_train = np.array(y_train).astype(np.float32)
X_train_norm = ((X_train-np.mean(X_train))/np.std(X_train))
X_train_norm = torch.from_numpy(X_train_norm)
y_train = torch.from_numpy(y_train)

train_ds = TensorDataset(X_train_norm, y_train)

batch_size = 1
train_dl = DataLoader(train_ds,
                      batch_size,
                      shuffle=True)

In [57]:
train_dl

## 4. Model Build

In [65]:
import torch.nn as nn

# 모델 구현
model = nn.Sequential(
    nn.Linear(143, 10, bias=True), # input layer
    nn.ReLU(), # activation function
    nn.Linear(10, 10, bias=True), # hidden layer
    nn.ReLU(),
    nn.Linear(10, 10, bias=True), # output layer
    nn.ELU(),
    nn.Linear(10, 10, bias=True) # output layer
    # nn.Sigmoid() # activation function
    )
criterion = nn.MSELoss()
optimizer = torch.optim.Adam(model.parameters(), lr=0.01)

## 5. Training

In [66]:
for epoch in range(200):
  for x_batch, y_batch in train_dl: # enumarate 안 쓴 경우
    pred = model(x_batch)

    loss = criterion(pred, y_batch)
    loss.backward()

    optimizer.step()
    optimizer.zero_grad()

  if epoch % 10 == 0:
    print(f'Epoch {epoch}: Loss {loss.item():.4f}')

Epoch 0: Loss 680.1642
Epoch 10: Loss 455.8429
Epoch 20: Loss 388.4424
Epoch 30: Loss 30.8980
Epoch 40: Loss 636.8550
Epoch 50: Loss 19.8657
Epoch 60: Loss 1950.9281
Epoch 70: Loss 35.7008
Epoch 80: Loss 1135.6145
Epoch 90: Loss 24.3158
Epoch 100: Loss 1418.5326
Epoch 110: Loss 11.7094
Epoch 120: Loss 43.1325
Epoch 130: Loss 9.5147
Epoch 140: Loss 23054.0527
Epoch 150: Loss 319.1991
Epoch 160: Loss 411.5081
Epoch 170: Loss 31.0231
Epoch 180: Loss 3419.2688
Epoch 190: Loss 260.5437

## 6. Prediction

In [67]:
X_test = np.array(X_test).astype(np.float32)
X_test_norm = (X_test - np.mean(X_train))/np.std(X_train)
X_test_norm = torch.from_numpy(X_test_norm)

y_pred = model(X_test_norm).detach().numpy() # no_grad를 한다.

In [68]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

def evaluate(y_test, y_pred):
  print('* MAE:', mean_absolute_error(y_test, y_pred))
  print('* RMSE:', np.sqrt(mean_absolute_error(y_test, y_pred)))
  print('* R_square:', r2_score(y_test, y_pred))

In [69]:
evaluate(y_test, y_pred)

* MAE: 20.003567111492156
* RMSE: 4.472534752407426
* R_square: 0.9512429888802888